# Site settings
title:          ImJurgen
description:    "My notes blog"
url:            "https://imjurgen.github.io/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jurgen
  url:          https://imjurgen.github.io/
  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         
